### ISSUE TITLE
Compiling openzoom.coffee

### ISSUE THREAD

**Issue by alacret** [openzoom/openzoom.js#1]
cofee openzoom.coffee

ReferenceError: window is not defined
    at Object.exports.parse (/home/alacret/Descargas/openzoom.js-master/lib/util/xml.coffee:6:9)
    at Function.DeepZoomImageDescriptor.fromXML (/home/alacret/Descargas/openzoom.js-master/lib/descriptors/deepzoom.coffee:45:17)
    at Object.<anonymous> (/home/alacret/Descargas/openzoom.js-master/lib/openzoom.coffee:43:39)
    at Object.<anonymous> (/home/alacret/Descargas/openzoom.js-master/lib/openzoom.coffee:100:4)
    at Module._compile (module.js:456:26)
    at Object.exports.run (/usr/lib/coffee-script/lib/coffee-script/coffee-script.js:83:25)
    at compileScript (/usr/lib/coffee-script/lib/coffee-script/command.js:177:29)
    at /usr/lib/coffee-script/lib/coffee-script/command.js:152:18
    at fs.js:268:14
    at Object.oncomplete (fs.js:107:15)

**Comment by gasi** [comment]
Thanks for bringing this up, but I ported the library away from CoffeeScript. It’s all very early, but please take another look.
